name: tf-next
recipe: drupal10
config:
  webroot: web
  php: 8.2

proxy:
  nextjs:
    - next.lndo.site:80

services:
  nextjs:
    api: 3
    type: lando
    scanner: false
    build:
      - cd next-ui
    services:
      image: node:18
      command: "yarn dev --port 80 --hostname 0.0.0.0"
      ports:
        - 80

tooling:
  node:
    service: nextjs
    dir: /app/next-ui
  npm:
    service: nextjs
    dir: /app/next-ui
  start-client:
    service: nextjs
    dir: /app/next-ui
    cmd: npm run dev -- --port 80 --hostname 0.0.0.0